### ISSUE TITLE
org-alert breaks the agenda

### ISSUE THREAD

**Issue by Chobbes** [spegoraro/org-alert#14] opened 2018-03-13 16:41 UTC
I was noticing that my org-agenda has been constantly breaking, and I finally figured out that it's because of org-alert!

Here's what happens:

- Open the agenda buffer
- Run org-alert-check (or let an alert happen)
- Try any command like `C-c C-s` to reschedule a task in the agenda 

I get the following message in the minibuffer, and nothing else happens:

    funcall-interactively: Wrong type argument: stringp, nil

I'm no longer able to change TODO state, schedule items, or do pretty much anything in the agenda without quitting the agenda view, and pulling it up again.

**Comment by spegoraro** [comment] 2018-04-14 04:14
Hi, thanks for reporting. I haven't been able to replicate the issue but please try master now. I have merged #16 from @PierreTechoueyres  which re-builds the agenda if a buffer exists so it may resolve what you're seeing.

**Comment by chase-dwelle** [comment] 2018-05-29 14:22
I can confirm that this is also happening for me using `org-alert-20180523.1833` from MELPA.

**Comment by PierreTechoueyres** [comment] 2018-05-29 22:15
Hi @chase-dwelle,
Could you try with redefining `org-alert-check` like bellow:
```elisp
(defun org-alert-check ()
  "Check for active, due deadlines and initiate notifications."
  (interactive)
  ;; avoid interrupting current command.
  (unless (minibufferp)
    (let ((org-agenda-saved-buffer (and org-agenda-buffer (buffer-name org-agenda-buffer))))
      (save-window-excursion
	(save-excursion
          (save-restriction
            (let ((active (org-alert--filter-active (org-alert--get-headlines))))
              (dolist (dl (org-alert--strip-states active))
		(alert dl :title org-alert-notification-title))))))
      (when org-agenda-saved-buffer
	(ignore-errors
    	  (with-current-buffer org-agenda-saved-buffer
    	    (org-agenda-redo t)))))))
```
If this correct your problem, I'll propose a new PR to fix this.

**Comment by chase-dwelle** [comment] 2018-05-29 22:19
That works but opens a new `org-agenda` buffer called `*temp*`, with the agenda functionality intact.

**Comment by PierreTechoueyres** [comment] 2018-05-29 22:27
I can't reproduce the creation of `*temp*` buffer.
How do you open the agenda buffer ? What's your version of org mode and Emacs ?

**Comment by chase-dwelle** [comment] 2018-05-29 22:31
Ah, the `*temp*` buffer is only created when I'm in one of my custom `agenda` layouts. The solution works for the "standard" `org-agenda`.

**Comment by PierreTechoueyres** [comment] 2018-05-29 22:37
Could you try the version bellow:
```elisp
(defun org-alert-check ()
  "Check for active, due deadlines and initiate notifications."
  (interactive)
  ;; avoid interrupting current command.
  (unless (minibufferp)
    (let ((org-agenda-saved-buffer (and org-agenda-buffer (buffer-name org-agenda-buffer))))
      (save-window-excursion
	(save-excursion
          (save-restriction
            (let ((active (org-alert--filter-active (org-alert--get-headlines))))
              (dolist (dl (org-alert--strip-states active))
		(alert dl :title org-alert-notification-title))))))
      (when org-agenda-saved-buffer
	(ignore-errors
    	  (with-current-buffer org-agenda-saved-buffer
    	    (org-agenda-redo-all t)))))))
```

**Comment by chase-dwelle** [comment] 2018-05-29 22:43
Still get the same behavior, duplicating the agenda into a `*temp*` buffer, unfortunately.

**Comment by PierreTechoueyres** [comment] 2018-05-29 22:57
And this one ?
```elisp
(defun org-alert-check ()
  "Check for active, due deadlines and initiate notifications."
  (interactive)
  ;; avoid interrupting current command.
  (unless (minibufferp)
    (let ((org-agenda-saved-buffer (and org-agenda-buffer (buffer-name org-agenda-buffer))))
      (save-window-excursion
	(save-excursion
          (save-restriction
            (let ((active (org-alert--filter-active (org-alert--get-headlines))))
              (dolist (dl (org-alert--strip-states active))
		(alert dl :title org-alert-notification-title))))))
      (when org-agenda-saved-buffer
	(ignore-errors
    	  (with-current-buffer org-agenda-saved-buffer
    	    (let ((org-agenda-this-buffer-name org-agenda-this-buffer-name))
	      (org-agenda-redo t))))))))
```

**Comment by chase-dwelle** [comment] 2018-05-30 01:49
Same thing. This is the custom view I'm using:
``` lisp
(setq org-agenda-custom-commands
      '(
        ;; Daily agenda perspectives
        ("d" . "Daily perspectives")    ;Label for daily perspectives.
        ("da" "Daily priority agenda"
         ((tags-todo "SCHEDULED<\"<+1d>\"&PRIORITY=\"A\"" ;Priority tasks available to do today
                     ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "High-priority unfinished tasks:")))
          (agenda "" ((org-agenda-span 'day)
                      (org-scheduled-delay-days -14)))
          (tags-todo "SCHEDULED<\"<+1d>\"" ;All tasks available today
                     ((org-agenda-skip-function '(or (org-agenda-skip-entry-if 'todo 'done)
                                                     (air-org-skip-subtree-if-priority ?A)))
                      (org-agenda-overriding-header "Available tasks:")))))))
```

**Comment by PierreTechoueyres** [comment] 2018-05-30 18:01
I think I won't be able to provide a better solution.
I think also that the right thing to do is to use the solution provided by @jakecoble in PR #17.

**Comment by jakecoble** [comment] 2018-05-31 17:32
@chase-dwelle What versions of Emacs and org are you using?

**Comment by chase-dwelle** [comment] 2018-05-31 19:44
I'm using Emacs 26.1 and org 9.1.13 from elpa.

**Comment by jakecoble** [comment] 2018-06-01 04:32
I think this deserves more attention, and I’ll look into it. As much as I like my solution, I don’t think we should merge a breaking change for a bug we haven’t been able to replicate yet.

@chase-dwelle For now, I suggest use my fork if it works around your problem (I’m currently running it successfully with Emacs 26 and org 9.)

**Comment by MCSH** [comment] 2020-08-05 12:56
Did you found any solutions for the rename of the custom agenda buffer to `*temp*`? I don't mind not being the default name, but I would prefer something that I can find in the buffers, like `*temp agenda*` at least.

**Comment by spegoraro** [comment] 2020-08-06 11:04
Unfortunately I've had very little time to work on this project, if anybody would like to take over maintenance I'll happily send the repo over. Otherwise at best I can have a look next month.

**Comment by leungbk** [comment] 2020-09-10 03:39
@spegoraro I'd be willing to take over the project if you've too little time on your hands.

**Comment by ntBre** [comment] 2021-08-28 18:39
I think this should be taken care of after the restructuring from #17, but I will be happy to reopen it if not.

**Closed as completed by ntBre** 2021-08-28 18:39 UTC
